<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Title>Sardanapal.Localization Tests</Title>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio" />
        <PackageReference Include="FluentAssertions" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Src\Sardanapal.Localization\Sardanapal.Localization.csproj" />
    </ItemGroup>

</Project>
