# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["master", "harpm/feature/golang-cicd"]
  pull_request:
    branches: ["master"]

jobs:
  update_share:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Add nuget source
        run: go run /home/runner/work/SardanapalCore/SardanapalCore/SDBuild.go