# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  update_share:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Add nuget source
        run: dotnet nuget add source --username harpm --password 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 --store-password-in-clear-text --name github "https://nuget.pkg.github.com/harpm/index.json"
      - name: Clean the build files
        run: dotnet clean /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.Share/Sardanapal.Share.csproj
      - name: Restore dependencies
        run: dotnet restore /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.Share/Sardanapal.Share.csproj
      - name: Build
        run: dotnet build /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.Share/Sardanapal.Share.csproj --no-restore --configuration release
      - name: Push package Share
        run: dotnet nuget push /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.Share/bin/release/*.nupkg -s https://nuget.pkg.github.com/harpm/index.json --skip-duplicate

  update_view_model:
    runs-on: ubuntu-latest

    concurrency:
      group: build
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Add nuget source
        run: dotnet nuget add source --username harpm --password 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 --store-password-in-clear-text --name github "https://nuget.pkg.github.com/harpm/index.json"
      - name: Clean the build files
        run: dotnet clean /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.ViewModel/Sardanapal.ViewModel.csproj
      - name: Restore dependencies
        run: dotnet restore /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.ViewModel/Sardanapal.ViewModel.csproj
      - name: Build
        run: dotnet build /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.ViewModel/Sardanapal.ViewModel.csproj --no-restore --configuration release
      - name: Push package ViewModel
        run: dotnet nuget push /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.ViewModel/bin/release/*.nupkg -s https://nuget.pkg.github.com/harpm/index.json --skip-duplicate

  update_domain_model:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Add nuget source
        run: dotnet nuget add source --username harpm --password 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 --store-password-in-clear-text --name github "https://nuget.pkg.github.com/harpm/index.json"
      - name: Clean the build files
        run: dotnet clean /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.DomainModel/Sardanapal.DomainModel.csproj
      - name: Restore dependencies
        run: dotnet restore /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.DomainModel/Sardanapal.DomainModel.csproj
      - name: Build
        run: dotnet build /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.DomainModel/Sardanapal.DomainModel.csproj --no-restore --configuration release
      - name: Push package DomainModel
        run: dotnet nuget push /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.DomainModel/bin/release/*.nupkg -s https://nuget.pkg.github.com/harpm/index.json --skip-duplicate

  update_redis_cach:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Add nuget source
        run: dotnet nuget add source --username harpm --password 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 --store-password-in-clear-text --name github "https://nuget.pkg.github.com/harpm/index.json"
      - name: Clean the build files
        run: dotnet clean /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.RedisCach/Sardanapal.RedisCach.csproj
      - name: Restore dependencies
        run: dotnet restore /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.RedisCach/Sardanapal.RedisCach.csproj
      - name: Build
        run: dotnet build /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.RedisCach/Sardanapal.RedisCach.csproj --no-restore --configuration release
      - name: Push package RedisCach
        run: dotnet nuget push /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.RedisCach/bin/release/*.nupkg -s https://nuget.pkg.github.com/harpm/index.json --skip-duplicate

  update_ef:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Add nuget source
        run: dotnet nuget add source --username harpm --password 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 --store-password-in-clear-text --name github "https://nuget.pkg.github.com/harpm/index.json"
      - name: Clean the build files
        run: dotnet clean /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.Ef/Sardanapal.Ef.csproj
      - name: Restore dependencies
        run: dotnet restore /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.Ef/Sardanapal.Ef.csproj
      - name: Build
        run: dotnet build /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.Ef/Sardanapal.Ef.csproj --no-restore --configuration release
      - name: Clean the build files
        run: dotnet clean /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.Ef/Sardanapal.Ef.csproj
      - name: Push package Ef
        run: dotnet nuget push /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.Ef/bin/release/*.nupkg -s https://nuget.pkg.github.com/harpm/index.json --skip-duplicate

  update_interface:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Add nuget source
        run: dotnet nuget add source --username harpm --password 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 --store-password-in-clear-text --name github "https://nuget.pkg.github.com/harpm/index.json"
      - name: Clean the build files
        run: dotnet clean /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.Interface/Sardanapal.Interface.csproj
      - name: Restore dependencies
        run: dotnet restore /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.Interface/Sardanapal.Interface.csproj
      - name: Build
        run: dotnet build /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.Interface/Sardanapal.Interface.csproj --no-restore --configuration release
      - name: Push package Interface
        run: dotnet nuget push /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.Interface/bin/release/*.nupkg -s https://nuget.pkg.github.com/harpm/index.json --skip-duplicate
  
  update_ef_services:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Add nuget source
        run: dotnet nuget add source --username harpm --password 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 --store-password-in-clear-text --name github "https://nuget.pkg.github.com/harpm/index.json"
      - name: Clean the build files
        run: dotnet clean /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.Ef.Service/Sardanapal.Ef.Service.csproj
      - name: Restore dependencies
        run: dotnet restore /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.Ef.Service/Sardanapal.Ef.Service.csproj
      - name: Build
        run: dotnet build /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.Ef.Service/Sardanapal.Ef.Service.csproj --no-restore --configuration release
      - name: Push package Ef Services
        run: dotnet nuget push /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.Ef.Service/bin/release/*.nupkg -s https://nuget.pkg.github.com/harpm/index.json --skip-duplicate
  
  update_http_service:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Add nuget source
        run: dotnet nuget add source --username harpm --password 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 --store-password-in-clear-text --name github "https://nuget.pkg.github.com/harpm/index.json"
      - name: Clean the build files
        run: dotnet clean /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.Http.Service/Sardanapal.Http.Service.csproj
      - name: Restore dependencies
        run: dotnet restore /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.Http.Service/Sardanapal.Http.Service.csproj
      - name: Build
        run: dotnet build /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.Http.Service/Sardanapal.Http.Service.csproj --no-restore --configuration release
      - name: Push package Http Service
        run: dotnet nuget push /home/runner/work/SardanapalCore/SardanapalCore/Sardanapal.Http.Service/bin/release/*.nupkg -s https://nuget.pkg.github.com/harpm/index.json --skip-duplicate
